language: php
php:
  - '5.6'

before_script:
  - curl -sSf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

script:
  - cd unit_test
  - phpunit --debug test_insertion.php
  - phpunit --debug test_suppression.php
  - phpunit --debug test_user_management.php
  - phpunit --debug test_chiffrement_database.php
